[package]
name = "trawler"
version = "0.3.3"

description = "A workload generator that emulates the traffic to lobste.rs"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]


documentation = "https://docs.rs/trawler"
homepage = "https://github.com/jonhoo/trawler"
repository = "https://github.com/jonhoo/trawler.git"

keywords = ["workload-generator", "traffic"]
categories = ["web-programming", "command-line-utilities", "development-tools::profiling", "simulation", "science"]

license = "MIT/Apache-2.0"

build = "data-import.rs"

[badges]
travis-ci = { repository = "jonhoo/tsunami" }

[features]
cli = ["clap", "hyper", "url", "regex", "lazy_static"]
default = ["cli"]

[dependencies]
slog = "2.0.6"
slog-term = "2.0.1"
libc = "0.2"
rand = "0.4.0"
zipf = "1.0.0"
hdrhistogram = "6.0.0"
histogram-sampler = "0.1.3"

multiqueue = "0.3.2"
tokio-core = "0.1"
futures = "0.1"

clap = { version = "2.25.0", optional = true }
hyper = { version = "0.11", optional = true }
url = { version = "1.7", optional = true }
regex = { version = "0.2", optional = true }
lazy_static = { version = "1.0.0", optional = true }

[build-dependencies]
glob = "0.2"

[profile.release]
debug = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "trawler"
path = "src/bin/main.rs"
required-features = ["cli"]
